/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GetOfferRouteImport } from './routes/get-offer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as SellFastRouteImport } from './routes/sell-fast'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as CrmImportRouteImport } from './routes/crm_.import'
import { Route as SellAbsenteeRouteImport } from './routes/sell/absentee'
import { Route as SellCodeViolationsRouteImport } from './routes/sell/code-violations'
import { Route as SellDivorceRouteImport } from './routes/sell/divorce'
import { Route as SellEvictionRouteImport } from './routes/sell/eviction'
import { Route as SellExpiredListingRouteImport } from './routes/sell/expired-listing'
import { Route as SellHighEquityRouteImport } from './routes/sell/high-equity'
import { Route as SellPreForeclosureRouteImport } from './routes/sell/pre-foreclosure'
import { Route as SellProbateRouteImport } from './routes/sell/probate'
import { Route as SellTaxDelinquentRouteImport } from './routes/sell/tax-delinquent'
import { Route as SellTiredLandlordRouteImport } from './routes/sell/tired-landlord'
import { Route as SellVacantRouteImport } from './routes/sell/vacant'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthStatusRouteImport } from './routes/api/auth/status'
import { Route as ApiOutreachDispatchRouteImport } from './routes/api/outreach/dispatch'
import { Route as ApiSkipTraceMonitorRouteImport } from './routes/api/skip-trace/monitor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GetOfferRoute = GetOfferRouteImport.update({
  id: '/get-offer',
  path: '/get-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const SellFastRoute = SellFastRouteImport.update({
  id: '/sell-fast',
  path: '/sell-fast',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmImportRoute = CrmImportRouteImport.update({
  id: '/crm_/import',
  path: '/crm/import',
  getParentRoute: () => rootRouteImport,
} as any)
const SellAbsenteeRoute = SellAbsenteeRouteImport.update({
  id: '/sell/absentee',
  path: '/sell/absentee',
  getParentRoute: () => rootRouteImport,
} as any)
const SellCodeViolationsRoute = SellCodeViolationsRouteImport.update({
  id: '/sell/code-violations',
  path: '/sell/code-violations',
  getParentRoute: () => rootRouteImport,
} as any)
const SellDivorceRoute = SellDivorceRouteImport.update({
  id: '/sell/divorce',
  path: '/sell/divorce',
  getParentRoute: () => rootRouteImport,
} as any)
const SellEvictionRoute = SellEvictionRouteImport.update({
  id: '/sell/eviction',
  path: '/sell/eviction',
  getParentRoute: () => rootRouteImport,
} as any)
const SellExpiredListingRoute = SellExpiredListingRouteImport.update({
  id: '/sell/expired-listing',
  path: '/sell/expired-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const SellHighEquityRoute = SellHighEquityRouteImport.update({
  id: '/sell/high-equity',
  path: '/sell/high-equity',
  getParentRoute: () => rootRouteImport,
} as any)
const SellPreForeclosureRoute = SellPreForeclosureRouteImport.update({
  id: '/sell/pre-foreclosure',
  path: '/sell/pre-foreclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const SellProbateRoute = SellProbateRouteImport.update({
  id: '/sell/probate',
  path: '/sell/probate',
  getParentRoute: () => rootRouteImport,
} as any)
const SellTaxDelinquentRoute = SellTaxDelinquentRouteImport.update({
  id: '/sell/tax-delinquent',
  path: '/sell/tax-delinquent',
  getParentRoute: () => rootRouteImport,
} as any)
const SellTiredLandlordRoute = SellTiredLandlordRouteImport.update({
  id: '/sell/tired-landlord',
  path: '/sell/tired-landlord',
  getParentRoute: () => rootRouteImport,
} as any)
const SellVacantRoute = SellVacantRouteImport.update({
  id: '/sell/vacant',
  path: '/sell/vacant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStatusRoute = ApiAuthStatusRouteImport.update({
  id: '/api/auth/status',
  path: '/api/auth/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOutreachDispatchRoute = ApiOutreachDispatchRouteImport.update({
  id: '/api/outreach/dispatch',
  path: '/api/outreach/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkipTraceMonitorRoute = ApiSkipTraceMonitorRouteImport.update({
  id: '/api/skip-trace/monitor',
  path: '/api/skip-trace/monitor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/briefing': typeof BriefingRoute
  '/buyers': typeof BuyersRoute
  '/calculator': typeof CalculatorRoute
  '/command-center': typeof CommandCenterRoute
  '/contracts': typeof ContractsRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/get-offer': typeof GetOfferRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/performance': typeof PerformanceRoute
  '/sell-fast': typeof SellFastRoute
  '/settings': typeof SettingsRoute
  '/thank-you': typeof ThankYouRoute
  '/crm/import': typeof CrmImportRoute
  '/sell/absentee': typeof SellAbsenteeRoute
  '/sell/code-violations': typeof SellCodeViolationsRoute
  '/sell/divorce': typeof SellDivorceRoute
  '/sell/eviction': typeof SellEvictionRoute
  '/sell/expired-listing': typeof SellExpiredListingRoute
  '/sell/high-equity': typeof SellHighEquityRoute
  '/sell/pre-foreclosure': typeof SellPreForeclosureRoute
  '/sell/probate': typeof SellProbateRoute
  '/sell/tax-delinquent': typeof SellTaxDelinquentRoute
  '/sell/tired-landlord': typeof SellTiredLandlordRoute
  '/sell/vacant': typeof SellVacantRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/outreach/dispatch': typeof ApiOutreachDispatchRoute
  '/api/skip-trace/monitor': typeof ApiSkipTraceMonitorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/briefing': typeof BriefingRoute
  '/buyers': typeof BuyersRoute
  '/calculator': typeof CalculatorRoute
  '/command-center': typeof CommandCenterRoute
  '/contracts': typeof ContractsRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/get-offer': typeof GetOfferRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/performance': typeof PerformanceRoute
  '/sell-fast': typeof SellFastRoute
  '/settings': typeof SettingsRoute
  '/thank-you': typeof ThankYouRoute
  '/crm/import': typeof CrmImportRoute
  '/sell/absentee': typeof SellAbsenteeRoute
  '/sell/code-violations': typeof SellCodeViolationsRoute
  '/sell/divorce': typeof SellDivorceRoute
  '/sell/eviction': typeof SellEvictionRoute
  '/sell/expired-listing': typeof SellExpiredListingRoute
  '/sell/high-equity': typeof SellHighEquityRoute
  '/sell/pre-foreclosure': typeof SellPreForeclosureRoute
  '/sell/probate': typeof SellProbateRoute
  '/sell/tax-delinquent': typeof SellTaxDelinquentRoute
  '/sell/tired-landlord': typeof SellTiredLandlordRoute
  '/sell/vacant': typeof SellVacantRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/outreach/dispatch': typeof ApiOutreachDispatchRoute
  '/api/skip-trace/monitor': typeof ApiSkipTraceMonitorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/briefing': typeof BriefingRoute
  '/buyers': typeof BuyersRoute
  '/calculator': typeof CalculatorRoute
  '/command-center': typeof CommandCenterRoute
  '/contracts': typeof ContractsRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/get-offer': typeof GetOfferRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/performance': typeof PerformanceRoute
  '/sell-fast': typeof SellFastRoute
  '/settings': typeof SettingsRoute
  '/thank-you': typeof ThankYouRoute
  '/crm_/import': typeof CrmImportRoute
  '/sell/absentee': typeof SellAbsenteeRoute
  '/sell/code-violations': typeof SellCodeViolationsRoute
  '/sell/divorce': typeof SellDivorceRoute
  '/sell/eviction': typeof SellEvictionRoute
  '/sell/expired-listing': typeof SellExpiredListingRoute
  '/sell/high-equity': typeof SellHighEquityRoute
  '/sell/pre-foreclosure': typeof SellPreForeclosureRoute
  '/sell/probate': typeof SellProbateRoute
  '/sell/tax-delinquent': typeof SellTaxDelinquentRoute
  '/sell/tired-landlord': typeof SellTiredLandlordRoute
  '/sell/vacant': typeof SellVacantRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/outreach/dispatch': typeof ApiOutreachDispatchRoute
  '/api/skip-trace/monitor': typeof ApiSkipTraceMonitorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/briefing'
    | '/buyers'
    | '/calculator'
    | '/command-center'
    | '/contracts'
    | '/crm'
    | '/dashboard'
    | '/get-offer'
    | '/login'
    | '/operations'
    | '/performance'
    | '/sell-fast'
    | '/settings'
    | '/thank-you'
    | '/crm/import'
    | '/sell/absentee'
    | '/sell/code-violations'
    | '/sell/divorce'
    | '/sell/eviction'
    | '/sell/expired-listing'
    | '/sell/high-equity'
    | '/sell/pre-foreclosure'
    | '/sell/probate'
    | '/sell/tax-delinquent'
    | '/sell/tired-landlord'
    | '/sell/vacant'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/status'
    | '/api/outreach/dispatch'
    | '/api/skip-trace/monitor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/briefing'
    | '/buyers'
    | '/calculator'
    | '/command-center'
    | '/contracts'
    | '/crm'
    | '/dashboard'
    | '/get-offer'
    | '/login'
    | '/operations'
    | '/performance'
    | '/sell-fast'
    | '/settings'
    | '/thank-you'
    | '/crm/import'
    | '/sell/absentee'
    | '/sell/code-violations'
    | '/sell/divorce'
    | '/sell/eviction'
    | '/sell/expired-listing'
    | '/sell/high-equity'
    | '/sell/pre-foreclosure'
    | '/sell/probate'
    | '/sell/tax-delinquent'
    | '/sell/tired-landlord'
    | '/sell/vacant'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/status'
    | '/api/outreach/dispatch'
    | '/api/skip-trace/monitor'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/briefing'
    | '/buyers'
    | '/calculator'
    | '/command-center'
    | '/contracts'
    | '/crm'
    | '/dashboard'
    | '/get-offer'
    | '/login'
    | '/operations'
    | '/performance'
    | '/sell-fast'
    | '/settings'
    | '/thank-you'
    | '/crm_/import'
    | '/sell/absentee'
    | '/sell/code-violations'
    | '/sell/divorce'
    | '/sell/eviction'
    | '/sell/expired-listing'
    | '/sell/high-equity'
    | '/sell/pre-foreclosure'
    | '/sell/probate'
    | '/sell/tax-delinquent'
    | '/sell/tired-landlord'
    | '/sell/vacant'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/status'
    | '/api/outreach/dispatch'
    | '/api/skip-trace/monitor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BriefingRoute: typeof BriefingRoute
  BuyersRoute: typeof BuyersRoute
  CalculatorRoute: typeof CalculatorRoute
  CommandCenterRoute: typeof CommandCenterRoute
  ContractsRoute: typeof ContractsRoute
  CrmRoute: typeof CrmRoute
  DashboardRoute: typeof DashboardRoute
  GetOfferRoute: typeof GetOfferRoute
  LoginRoute: typeof LoginRoute
  OperationsRoute: typeof OperationsRoute
  PerformanceRoute: typeof PerformanceRoute
  SellFastRoute: typeof SellFastRoute
  SettingsRoute: typeof SettingsRoute
  ThankYouRoute: typeof ThankYouRoute
  CrmImportRoute: typeof CrmImportRoute
  SellAbsenteeRoute: typeof SellAbsenteeRoute
  SellCodeViolationsRoute: typeof SellCodeViolationsRoute
  SellDivorceRoute: typeof SellDivorceRoute
  SellEvictionRoute: typeof SellEvictionRoute
  SellExpiredListingRoute: typeof SellExpiredListingRoute
  SellHighEquityRoute: typeof SellHighEquityRoute
  SellPreForeclosureRoute: typeof SellPreForeclosureRoute
  SellProbateRoute: typeof SellProbateRoute
  SellTaxDelinquentRoute: typeof SellTaxDelinquentRoute
  SellTiredLandlordRoute: typeof SellTiredLandlordRoute
  SellVacantRoute: typeof SellVacantRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthStatusRoute: typeof ApiAuthStatusRoute
  ApiOutreachDispatchRoute: typeof ApiOutreachDispatchRoute
  ApiSkipTraceMonitorRoute: typeof ApiSkipTraceMonitorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-offer': {
      id: '/get-offer'
      path: '/get-offer'
      fullPath: '/get-offer'
      preLoaderRoute: typeof GetOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-fast': {
      id: '/sell-fast'
      path: '/sell-fast'
      fullPath: '/sell-fast'
      preLoaderRoute: typeof SellFastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm_/import': {
      id: '/crm_/import'
      path: '/crm/import'
      fullPath: '/crm/import'
      preLoaderRoute: typeof CrmImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/absentee': {
      id: '/sell/absentee'
      path: '/sell/absentee'
      fullPath: '/sell/absentee'
      preLoaderRoute: typeof SellAbsenteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/code-violations': {
      id: '/sell/code-violations'
      path: '/sell/code-violations'
      fullPath: '/sell/code-violations'
      preLoaderRoute: typeof SellCodeViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/divorce': {
      id: '/sell/divorce'
      path: '/sell/divorce'
      fullPath: '/sell/divorce'
      preLoaderRoute: typeof SellDivorceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/eviction': {
      id: '/sell/eviction'
      path: '/sell/eviction'
      fullPath: '/sell/eviction'
      preLoaderRoute: typeof SellEvictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/expired-listing': {
      id: '/sell/expired-listing'
      path: '/sell/expired-listing'
      fullPath: '/sell/expired-listing'
      preLoaderRoute: typeof SellExpiredListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/high-equity': {
      id: '/sell/high-equity'
      path: '/sell/high-equity'
      fullPath: '/sell/high-equity'
      preLoaderRoute: typeof SellHighEquityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/pre-foreclosure': {
      id: '/sell/pre-foreclosure'
      path: '/sell/pre-foreclosure'
      fullPath: '/sell/pre-foreclosure'
      preLoaderRoute: typeof SellPreForeclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/probate': {
      id: '/sell/probate'
      path: '/sell/probate'
      fullPath: '/sell/probate'
      preLoaderRoute: typeof SellProbateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/tax-delinquent': {
      id: '/sell/tax-delinquent'
      path: '/sell/tax-delinquent'
      fullPath: '/sell/tax-delinquent'
      preLoaderRoute: typeof SellTaxDelinquentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/tired-landlord': {
      id: '/sell/tired-landlord'
      path: '/sell/tired-landlord'
      fullPath: '/sell/tired-landlord'
      preLoaderRoute: typeof SellTiredLandlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/vacant': {
      id: '/sell/vacant'
      path: '/sell/vacant'
      fullPath: '/sell/vacant'
      preLoaderRoute: typeof SellVacantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/status': {
      id: '/api/auth/status'
      path: '/api/auth/status'
      fullPath: '/api/auth/status'
      preLoaderRoute: typeof ApiAuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/outreach/dispatch': {
      id: '/api/outreach/dispatch'
      path: '/api/outreach/dispatch'
      fullPath: '/api/outreach/dispatch'
      preLoaderRoute: typeof ApiOutreachDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skip-trace/monitor': {
      id: '/api/skip-trace/monitor'
      path: '/api/skip-trace/monitor'
      fullPath: '/api/skip-trace/monitor'
      preLoaderRoute: typeof ApiSkipTraceMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  BriefingRoute: BriefingRoute,
  BuyersRoute: BuyersRoute,
  CalculatorRoute: CalculatorRoute,
  CommandCenterRoute: CommandCenterRoute,
  ContractsRoute: ContractsRoute,
  CrmRoute: CrmRoute,
  DashboardRoute: DashboardRoute,
  GetOfferRoute: GetOfferRoute,
  LoginRoute: LoginRoute,
  OperationsRoute: OperationsRoute,
  PerformanceRoute: PerformanceRoute,
  SellFastRoute: SellFastRoute,
  SettingsRoute: SettingsRoute,
  ThankYouRoute: ThankYouRoute,
  CrmImportRoute: CrmImportRoute,
  SellAbsenteeRoute: SellAbsenteeRoute,
  SellCodeViolationsRoute: SellCodeViolationsRoute,
  SellDivorceRoute: SellDivorceRoute,
  SellEvictionRoute: SellEvictionRoute,
  SellExpiredListingRoute: SellExpiredListingRoute,
  SellHighEquityRoute: SellHighEquityRoute,
  SellPreForeclosureRoute: SellPreForeclosureRoute,
  SellProbateRoute: SellProbateRoute,
  SellTaxDelinquentRoute: SellTaxDelinquentRoute,
  SellTiredLandlordRoute: SellTiredLandlordRoute,
  SellVacantRoute: SellVacantRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthStatusRoute: ApiAuthStatusRoute,
  ApiOutreachDispatchRoute: ApiOutreachDispatchRoute,
  ApiSkipTraceMonitorRoute: ApiSkipTraceMonitorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
